from .train_scratch_epoch import train_scratch_per_epoch
from .train_scratch import train_from_scratch
from .train_scratch_unsup import train_from_scratch_unsup

from .train_scratch_vox import train_from_scratch_vox
from .train_scratch_unsup_vox import train_from_scratch_unsup_vox


from .train_epoch_cont_unsupervised_selective import (
    train_per_epoch_contrastive_unsupervised_selective,
)


from .train_cont_unsupervised import train_contrastive_unsupervised
from .train_cont_supervised import train_contrastive_supervised

from .train_cont_supervised_vox import train_contrastive_supervised_vox
from .train_cont_unsupervised_vox import train_contrastive_unsupervised_vox